### ISSUE TITLE
[Wiki] Update DNS Server Configuration with examples for dnsmasq and Windows DNS

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos#11]
Reminder to self: contribute examples for dnsmasq and Windows DNS to the configuration guide at https://github.com/AMWA-TV/nmos/wiki/Configuration-Guide#dns-server-configuration.

**Comment by garethsb-sony** [comment]
Done, though it can no doubt be improved on!

**Comment by andrewbonney** [comment]
Thanks Gareth. I noted the _services records for dnsmasq weren't listed. Could you see if the following looks right to you and if so I can always add it in:

```
ptr-record=_services._dns-sd._udp.dns.nmos.tv,_nmos-registration._tcp.dns.nmos.tv
ptr-record=_services._dns-sd._udp.dns.nmos.tv,_nmos-query._tcp.dns.nmos.tv
```

**Comment by garethsb-sony** [comment]
I saw those in the BIND config; I didn't put those in for my examples because I haven't needed them. I see now they're for [Service Type Enumeration](https://tools.ietf.org/html/rfc6763#section-9) to make ``avahi-browse -a`` and the like work? I hadn't been able to make this work yet, but I'll give it a go.

**Comment by andrewbonney** [comment]
Yeah that's the idea, purely useful for debug, it shouldn't have an effect on the ability of a Node to find a registry etc.
