### ISSUE TITLE
Typo on DNS configuration wiki page

### ISSUE THREAD

**Issue by daniel-pebble** [AMWA-TV/nmos#12]
Hi @andrewbonney,

There is typo on this page; https://github.com/AMWA-TV/nmos/wiki/Configuration-Guide
Under the windows dns section;
`Text (TXT)
Record name: reg-api-1._nmos-query._tcp
Fully qualified domain name (FQDN): reg-api-1._nmos-registration._tcp.dns.nmos.tv`

Should be; "Record name: reg-api-1._nmos-registration._tcp"
`Text (TXT)
Record name: reg-api-1._nmos-registration._tcp
Fully qualified domain name (FQDN): reg-api-1._nmos-registration._tcp.dns.nmos.tv`

FYI I tried to push this change via a new branch but I guess I don't have permission to push changes into the wiki repo.  

Thanks,
Daniel

**Comment by andrewbonney** [comment]
Thanks Daniel. That should now be fixed: https://github.com/AMWA-TV/nmos/wiki/Configuration-Guide/_compare/d1e8bd75e75a60bf5b0fa37724bffc33d055f3f1...35ada2507ded4493e64e7e767db0ab9bf778871d
