### ISSUE TITLE
Problems in NMOS Technical Overview

### ISSUE THREAD

**Issue by firthmj** [AMWA-TV/nmos#13]
Hi,

A couple of the sections of the NMOS Technical Overview are incomplete / corrupt.

In particular, the "Technology independence through data modelling" section has a carriage return about half way through, and then a line starts with "and then", and the resulting sentence doesn't make sense. Even replacing "and then" with "are then" and removing the extra carriage return doesn't help, as you end up with "The HTTP/WebSockets/RAML/JSON are then mapped these to JSON/HTTP/WebSockets/whatever", as this is basically saying "A is mapped to A". The last sentence also cuts off without finishing.

The "Self-documenting specifications" section also cuts off two words into a sentence.

Would someone have time to review these paragraphs and work out what they are supposed to say?

Thanks

**Comment by andrewbonney** [comment]
Thanks for spotting this. I've mentioned it to @peterbrightwell and we'll try and get it sorted as soon as possible.

**Comment by peterbrightwell** [comment]
I've fixed the "A mapped to A" para, removed the incomplete sentence, which is now less relevant, and fixed the third one.
