### ISSUE TITLE
Specification structure overview

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos#17]
I've had a comment that for new users it would be useful to provide a brief indication of how to navigate the specifications. This links in part with https://github.com/AMWA-TV/nmos-template/issues/3

Perhaps ahead of the 'Specifications' section of the technical overview we could provide a brief navigation guide talking about the general spec layout: where to find the HTML rendered RAML, what's in the docs, and how to find the detail contained within the schema files.

**Comment by peterbrightwell** [comment]
I've added a "Reading the Specifications" section on the pb-updated-overview branch. @andrewbonney can you take a look before I do a PR.

Note that this includes an apology for Gareth's $ref issue but I'll look into that soon.

**Comment by andrewbonney** [comment]
Thanks Pete, that's much better. One minor typo spotted: 'documentats'.
