### ISSUE TITLE
Update Nextera Video's Media Node product listing on NMOS Solutions page

### ISSUE THREAD

**Issue by psnguyen** [AMWA-TV/nmos#20]
Nextera Video's product listing for "NMOS Software Core" is out of date w.r.t the "Supported Specifications". 

Company: _Nextera Video_
Product: _NMOS Software Core_ (http://www.nexteravideo.com/nmos)
Supported Specifications: _IS-04 v1.3, IS-05 v1.1, IS-08 v1.0_
Comments: _Software core for FPGA embedded or standalone processor_

**Comment by andrewbonney** [comment]
Done. Thanks for the update.
