### ISSUE TITLE
Specification uniformity

### ISSUE THREAD

**Issue by a1800bert** [AMWA-TV/nmos#21]
It would be good in the future to take a look at previous specification details before doing a new one.

We could try to standardize the API, as for example, IS05 and IS08 as both activation mechanism but they are totally different ones.. While it could have been easy to use the same mechanism

activation/single
activation/bulk
...

**Comment by peterbrightwell** [comment]
This is of course an important general point.  Now we have more architecture governance in place AMWA should be better placed to ensure this happens.  Closing this issue as it doesn't specifcally need a change to this repo.
