### ISSUE TITLE
NMOS Solutions table entry needs an update (Dalet)

### ISSUE THREAD

**Issue by sergekorolev** [AMWA-TV/nmos#22]
Hello,

Dalet's entry for Brio video server needs to be updated at:
https://github.com/AMWA-TV/nmos/wiki/NMOS-Solutions

The current implementation includes support for 
- IS-04 v1.3 
- IS-05 v1.1
- IS-08 v1.0

The datasheet can be downloaded from the product web page at 
https://www.dalet.com/platforms/brio
or following this link
https://www.dalet.com/sites/default/files/2020-04/Dalet%20Brio%20Datasheet%20-%203.19.pdf

Thanks
Serge

**Comment by garethsb-sony** [comment]
Looks good, Serge!

Resolved by https://github.com/AMWA-TV/nmos/wiki/NMOS-Solutions/78b25d8075291e390aa8ac7beb481143510b1c5e
