### ISSUE TITLE
Glossary link broken

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos#23]
**NMOS Technical Overview** has a link to Glossary.md which exists in the wiki not the main repo.
On the rendered page at https://amwa-tv.github.io/nmos/branches/master/NMOS_Technical_Overview.html that becomes a link to a copy of the raw markdown at https://amwa-tv.github.io/nmos/branches/master/Glossary.md, rather than a rendered version.

**Comment by peterbrightwell** [comment]
Closing as we've moved things to https://specs.amwa.tv/ and checking links anyway.
