### ISSUE TITLE
New commercial implementation of the NMOS specifications

### ISSUE THREAD

**Issue by FXsan** [AMWA-TV/nmos#25]
Hello,

The following equipment is now available :
- TITAN Live from ATEME, https://www.ateme.com/titan-live/
broadcast encoder / transcoder multi codecs, multi outputs (TS, HLS, DASH, MSS, etc), managing 2110 inputs in addition to TS, SDI, RF, 2022-6/7, ...
- IS-04 v1.3
- IS-05 v1.1 

can you please list it in your section Commercial Hardware & Software in page https://amwa-tv.github.io/nmos/branches/master/NMOS-Solutions.html

Looking forward participating to the next JT-NM interop Fest !

Thanks in advance
FX

**Comment by garethsb-sony** [comment]
That sounds exciting, congratulations!

At the moment, I don't see where on https://www.ateme.com/titan-live/ or the linked data sheet, the NMOS capabilities are mentioned?

**Comment by peterbrightwell** [comment]
Hi there - as we're updating the NMOS spec and docs pages, I'm taking a look at the NMOS Solutions page. As Gareth mentions, we will need a link with reference to supported specs and versions.

**Comment by peterbrightwell** [comment]
@FXsan I'll be updating this list soon -- any update on your info?

**Comment by peterbrightwell** [comment]
@FXsan it would be good to get this issue resolved -- any update?

**Comment by peterbrightwell** [comment]
@FXsan I'll close this issue for now.  Feel free to reopen when the Titan page is updated to include NMOS information!
