### ISSUE TITLE
Another Controller to add (belatedly)

### ISSUE THREAD

**Issue by jmailhot** [AMWA-TV/nmos#26]
Hi Peter, please add our controller to the NMOS Solutions page under commercial / controllers.

Company= Imagine Communications
Product= Magellan SDNO
Spec= IS-04 v1.2  IS-05 v1.0
Comments = "Broadcast Routing Systems Controller for IP (NMOS and non-NMOS) and Legacy Systems.  Includes optional IS-04 Registry"

**Comment by peterbrightwell** [comment]
Hi John -- can you provide a product URL that includes reference to the suported specs?

Thanks
Pete

**Comment by peterbrightwell** [comment]
@jmailhot as we're updating the NMOS spec and docs pages, I'm taking a look at the NMOS Solutions page.  Do you have a link that includes the NMOS specs and versions supported?

**Comment by peterbrightwell** [comment]
@jmailhot any update on this?

**Comment by jmailhot** [comment]
https://imaginecommunications.com/product/magellan-sdn-orchestrator/

under "features"   --

   - Leverages AMWA NMOS IS-04 and IS-05 to integrate compliant 3rd party
   devices without special drivers

**Comment by peterbrightwell** [comment]
Added in https://github.com/AMWA-TV/nmos/commit/0944b61542f50208218944c035a20b6ca4a1d41c
