### ISSUE TITLE
Elevate NMOS Discovery & Registration WIP to Proposed Specification

### ISSUE THREAD

**Issue by bgilmer77** [AMWA-TV/nmos#4]
The AMWA Board of Directors has voted to approve the elevation of the NMOS Discovery & Registration WIP to Proposed Specification.  
@peterbrightwell Please change all notations of WIP to Proposed Specification in the git repository.

Note - the approved long name for this project is IS-04 NMOS Discovery & Registration Proposed Specification.  It will be tagged version 1.0.

**Comment by peterbrightwell** [comment]
The Discovery and Registration Specification is now in a separate repo: nmos-discovery-registration, with these changes. (Also the In-stream Identity and Timing Specification is now in nmos-in-stream-id-timing.)
