### ISSUE TITLE
Calrec Audio NMOS Implementations

### ISSUE THREAD

**Issue by dave1k99** [AMWA-TV/nmos#42]
Calrec Audio are currently shipping the following products with IS-04 v 1.3 and IS-05 v1.1:

- Impulse
- Type-R
- Type-R IO
- Modular IO
- Fixed Format IO
- Hydra2 IP Gateway

Product pages can be found here: [https://calrec.com/products/](https://calrec.com/products/)

I am told that the product pages are currently being updated to include NMOS within their feature lists, expect to see them there by the end of this week. Can these be added to the implementation list? Please feel free to contact me for any clarification.

Dave

**Comment by peterbrightwell** [comment]
Thanks @dave1k99.  To help us, could you provide for each product a brief description of its functionality and a URL to the product page that shows the spec and version numbers supported (I see some mention of NMOS, but is there anything more specific yet?)

**Comment by dave1k99** [comment]
Thanks Peter, I will have the version numbers updated and get back to you with the necessary information.

**Comment by peterbrightwell** [comment]
Hi @dave1k99 any update on this?

**Comment by dave1k99** [comment]
Hi Peter,

Yes, apologies for the delay. We've got all the specs updated on the website, I just need to collate all the information for you. Will get this done by Monday.

Dave

**Comment by dave1k99** [comment]
All of the below products are operating with v1.3 IS-04 and v1.1 IS-05.

- Impulse - Audio Mixing Console - https://calrec.com/shop/broadcast-audio-consoles/impulse/
- Hydra2 IP Gateway - Hydra2/ST2110/AES67 Conversion - https://calrec.com/shop/audio-networking/gateway/
- Type-R Core - Audio Mixing Console - https://calrec.com/shop/broadcast-audio-consoles/type-r-for-radio/
- Type-R Analogue IO - Analgoue/ST2110/AES67 Gateway - https://calrec.com/shop/broadcast-audio-consoles/type-r-for-radio/
- Type-R Digital IO - AES3/ST2110/AES67 Gateway - https://calrec.com/shop/broadcast-audio-consoles/type-r-for-radio/
- Type-R Combo IO - Analogue/AES3/ST2110/AES67 Gateway - https://calrec.com/shop/broadcast-audio-consoles/type-r-for-radio/
- Fixed Format IO - Analogue/AES3/ST2110/AES67 Gateway - https://calrec.com/shop/audio-networking/hydra/
- Modular IO - MADI/SDI/DANTE/Analogue/AES3/Waves/ST2110/AES67 Gateway - https://calrec.com/shop/audio-networking/hydra/

**Comment by peterbrightwell** [comment]
Thanks @dave1k99 that's an impressive set!  Now added, but please check. To save space I've combined the comments for the five gateway products.

**Comment by peterbrightwell** [comment]
PS NB the product page is now https://specs.amwa.tv/nmos/branches/main/docs/NMOS_Solutions.html  (no document number)

**Comment by dave1k99** [comment]
@peterbrightwell, just one typo on the "combo" box, you've got it down as a "combi". Other than that, looks great, many thanks.

**Comment by peterbrightwell** [comment]
Typo fixed
