### ISSUE TITLE
New Media Nodes to add to the NMOS Solution page

### ISSUE THREAD

**Issue by pimiller** [AMWA-TV/nmos#49]
Hi,

Synamedia would like to add the following product to the Media Nodes section of the NMOS Solution page:

Product: Virtual Digital Content Manager (vDCM)
Datasheet: http://www.synamedia.com/wp-content/uploads/2021/11/VN-vDCM-Encoder-Datasheet.pdf 
Supported Specifications: IS-04 v1.3, IS05 v1.1, BCP-002-01 v1.0, BCP-004-01 v1.0
Comment: Software-based video multiplexer and compression system (encoder/transcoder), supporting AMWA NMOS

Regards,
Pierre Miller

**Comment by peterbrightwell** [comment]
Added in #50
