### ISSUE TITLE
New Media Nodes to add to the NMOS Solution page

### ISSUE THREAD

**Issue by pimiller** [AMWA-TV/nmos#55]
Hi,

Synamedia would like to add the following product to the Media Nodes section of the NMOS Solution page:

Product: Media Edge Gateway (MEG)
Datasheet: https://www.synamedia.com/wp-content/uploads/2021/11/VN-Media-Edge-Gateway-Datasheet.pdf
Supported Specifications: IS-04 v1.3, IS-05 v1.1, BCP-002-01 v1.0, BCP-004-01 v1.0
Comment: Comprehensive cloud-native edge reception and processing platform

Regards,
Pierre Miller

**Comment by garethsb** [comment]
Looks good. Worth including a link to the web page, https://www.synamedia.com/video-solutions/video-network/video-network-products/, as well, @pimiller?

It'd be nice if the datasheet mentioned the versions of IS-04 and -05, and BCP-002-01 v1.0, BCP-004-01 v1.0, but I don't know if that's critical, @peterbrightwell?

**Comment by pimiller** [comment]
Thanks Gareth - yes, please include the link to the webpage you mention.

As for adding the specific NMOS standard in the datasheet, I'll see what I can do.

**Comment by pimiller** [comment]
The Monitoring and Management section includes this:
• AMWA IS-04 NMOS Discovery and Registration
• AMWA IS-05 NMOS Device Connection Management

Is this sufficient?

**Comment by peterbrightwell** [comment]
See #56.  I've just added the datasheet link... with our current table structure there's not an obvious place to add a second link but suggestions welcome.

**Comment by peterbrightwell** [comment]
Sorry for the delay in reviewing. This is now merged and appears on the rendered page.
