### ISSUE TITLE
New product request: \[COMPANY\]

### ISSUE THREAD

**Issue by debresserp** [AMWA-TV/nmos#73]
AMWA maintains a list of NMOS-capable implementations [here](https://specs.amwa.tv/nmos/branches/main/docs/NMOS_Solutions.html).  To request an addition please complete the following information (repeat as required for multiple products), add your company name to the issues title (as well as below), and submit the issue.

**Company name** Grass Valley

**Type of product** LDX 150 / LDX 135

> Node, Controller or registry Node

**Product name and link to information** LDX 150 (Live Broadcast Camera)

> Please use this form: `[Name](URL)` https://www.grassvalley.com/products/cameras/ldx-100-series/ldx-150/#
> It must be possible to find information about the supported specifications via the URL. If this is not obvious, please add a suitable comment to help

**Supported specifications** IS-04 v1.3, IS-05 v1.1

> Must include the latest supported version, e.g. "IS-04 v1.3".

**Comments**

> Such as the function of the product. Please keep brief.

**Comment by peterbrightwell** [comment]
Updated in 9a5173b57991452a50bd83eb2be4f4272803d1ab. Apologies for the delay.
