### ISSUE TITLE
New product request: \[Macnica\]

### ISSUE THREAD

**Issue by sato-mak** [AMWA-TV/nmos#75]
AMWA maintains a list of NMOS-capable implementations [here](https://specs.amwa.tv/nmos/branches/main/docs/NMOS_Solutions.html).  To request an addition please complete the following information (repeat as required for multiple products), add your company name to the issues title (as well as below), and submit the issue.

**Company name**
Macnica

**Type of product**
Node

**Product name and link to information**

[Media Over IP Package](https://www.m-pression.com/solutions/hardware-software/media-over-ip-package)
[EASYSS10 EVK](https://www.m-pression.com/solutions/hardware-software/easyss)
[M2S SDK](https://www.m-pression.com/solutions/software/m2s_sdk)

Please REMOVE current [VIPA] product because it had been terminated.

**Supported specifications**

IS-04 v1.3
IS-05 v1.1

**Comments**

[Media Over IP Package] : ST2110 FPGA & Software IP Core 
[EASYSS10 EVK] : SDI to IP Gateway Evaluation kit
[M2S SDK] : ST2110 Streaming Software Development kit

**Comment by peterbrightwell** [comment]
Added in e7c7273bb592f60104d59da863077f2bff0b77c8. Apologies for the delay.
