### ISSUE TITLE
New product request: \[MediaKind\]

### ISSUE THREAD

**Issue by hocinebelhous** [AMWA-TV/nmos#76]
AMWA maintains a list of NMOS-capable implementations [here](https://specs.amwa.tv/nmos/branches/main/docs/NMOS_Solutions.html).  To request an addition please complete the following information (repeat as required for multiple products), add your company name to the issues title (as well as below), and submit the issue.

**Company name**
> MediaKind

**Type of product**
> Node

**Product name and link to information**
> MediaKind RX1. Link to data-sheet: [MediaKind RX1](https://www.mediakind.com/wp-content/uploads/2020/10/RX1-Datasheet.pdf)
> We do not specify the NMOS versions supported but I will work on that.

**Supported specifications**
> NMOS IS-04 v1.0, v1.1, v1.2 and v1.3
> NMOS IS-05 v1.0 and v1.1

**Comments**
> The MediaKind RX1 is an edge capable of decoding video up to 4:2:2 UHD resolution and offer other functions such as decryption, transcode and network adaptation with Satellite input, ASI, SDI/SMPTE ST 2110 output, Ad insertion, SRT and Zixi.

**Company name**
> MediaKind

**Type of product**
> Node

**Product name and link to information**
> MediaKind CE1. Link to data-sheet: [MediaKind CE1](https://www.mediakind.com/wp-content/uploads/2020/10/CE1-Datasheet.pdf)
> We do not specify the NMOS versions supported but I will work on that.

**Supported specifications**
> NMOS IS-04 v1.0, v1.1, v1.2 and v1.3
> NMOS IS-05 v1.0 and v1.1

**Comments**
> The MediaKind CE1 is a contribution encoder capable of encoding video up to 4:2:2 UHD resolution and offer other functions such as encryption and remultiplexing. It supports SDI/SMPTE ST 2110 input and can ingest streams from ASI, IP, SRT and Zixi.

**Company name**
> MediaKind

**Type of product**
> Node

**Product name and link to information**
> MediaKind Aquila. Link to data-sheet: [MediaKind Aquila](https://www.mediakind.com/wp-content/uploads/2020/10/Aquila-Broadcast-Datasheet.pdf)
> We do not specify the NMOS versions supported but we will work on that.

**Supported specifications**
> NMOS IS-04 v1.0, v1.1, v1.2 and v1.3
> NMOS IS-05 v1.0 and v1.1

**Comments**
> MediaKind Aquila is a solution for broadcast compression head-ends based around MediaKind’s software encoder for both live linear broadcast and streaming application and uses MediaKind's transport stream multiplexer and scrambler. It offer a rich set of features and can be deployed on dedicated hardware or in a cloud environment.

**Comment by peterbrightwell** [comment]
Added in 02ed44bd67b9d53b808b69526602e15bf4bcf605. Apologies for the delay.
