### ISSUE TITLE
New product request: \[Panasonic Connect\]

### ISSUE THREAD

**Issue by ishibashihideaki** [AMWA-TV/nmos#77]
AMWA maintains a list of NMOS-capable implementations [here](https://specs.amwa.tv/nmos/branches/main/docs/NMOS_Solutions.html).  To request an addition please complete the following information (repeat as required for multiple products), add your company name to the issues title (as well as below), and submit the issue.

**Company name**
Panasonic Connect

**Type of product**
Media Nodes

**Product name and link to information**
[KAIROS AT-KC100](https://pro-av.panasonic.net/en/products/it_ip_platform/)
[KAIROS AT-KC1000](https://pro-av.panasonic.net/en/products/it_ip_platform/)
[AK-NP600 10G MoIP Board for AK-UCU600](https://pro-av.panasonic.net/en/products/ak-np600g/)

**Supported specifications**
IS-04 v1.3
IS-05 v1.1

**Comments**
[KAIROS AT-KC100]: Live Video Production Platform
[KAIROS AT-KC1000]: Live Video Production Platform
[AK-NP600 10G MoIP Board for AK-UCU600]: Camera Control Unit for Studio Camera System

**Comment by peterbrightwell** [comment]
Added in 1b3a15b70704a9e992ec9a31311443bac7b3cf11. Apologies for the delay.

**Comment by ishibashihideaki** [comment]
Thank you very much, Peter.

**Comment by ishibashihideaki** [comment]
Sorry, some text is different from what I asked.  The third product name should be "AK-NP600 10G MoIP Board for AK-UCU600", not "AK-NP600 10 MoIP Board". Could you possibley correct the text?

**Comment by ishibashihideaki** [comment]
Hello,

Thank you very much for the updates.

There is just one thing.
Some text is different from what I asked.
The third product name from Panasonic should be "AK-NP600 10G MoIP Board for AK-UCU600", not "AK-NP600 10 MoIP Board".
Could you kindly correct the text?

Thank you very much, again.

Best regards,

Hideaki Ishibashi

----------------------------------------------------------------------
Professional AV Technology Group
Media & Entertainment Business Division
Panasonic Connect Co., Ltd.
E-mail : ***@***.******@***.***>
----------------------------------------------------------------------

**Comment by ishibashihideaki** [comment]
Thank you very much, Peter.

Sorry again, very close but just “G” is missing after “10”.
I would like it to be “AK-NP600 10G MoIP Board for AK-UCU600”.

Thank you.

Regards,

Hideaki Ishibashi

**Comment by ishibashihideaki** [comment]
It's perfect now. Thank you so much!
